# Generated by Django 4.1 on 2023-01-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tour_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('number_card', models.CharField(max_length=50, verbose_name='Номер карты')),
                ('Name_of_the_card_holder', models.CharField(max_length=60, verbose_name='Имя владельца карты')),
                ('cvc', models.CharField(max_length=50)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tour')),
            ],
        ),
    ]
