# Generated by Django 4.1 on 2023-01-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_reservationhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationhotel',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hotel'),
        ),
    ]
